name: icon_decoration
description: Add decoration capabilities for the Icon widget with shadows, borders, gradients.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  golden_toolkit: ^0.10.0

flutter:
  uses-material-design: true
