name: icon_decoration
description: Add decoration capabilities for the Icon widget with shadows,
  borders, gradients.
version: 2.0.0
homepage: https://github.com/TesteurManiak/icon_decoration
repository: https://github.com/TesteurManiak/icon_decoration
issue_tracker: https://github.com/TesteurManiak/icon_decoration/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  alchemist: ^0.6.0
  fd_lints: ^1.1.0
  flutter_test:
    sdk: flutter
  meta: ^1.9.1

flutter:
  uses-material-design: true
  # Used for readable platform golden tests.
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
