name: Test workflow

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2.10.0
    - run: flutter pub get
    - name: Test
      run: flutter test --coverage --dart-define=CI=true
    - name: Collect and report coverage
      uses: coverallsapp/github-action@v2.1.2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}